WebRepository/Areas/ClaimsArea/Controllers/ClaimsController.cs
using System.Linq;
using System.Threading.Tasks;


using ModelLayer.ViewModelLayer.Claims;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using AllServises.Claims;

namespace WebRepository.Areas.ClaimsArea.Controllers {
    [Area("ClaimsArea")]
    //[Authorize(Roles = "Owner")]
    //[Authorize(Roles = "Admin")]
    public class ClaimsController : Controller {
        private readonly UserManager<IdentityUser> _UserManager;
        private readonly RoleManager<IdentityRole> _RoleManager;

        public ClaimsController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager) {
            _UserManager = userManager;
            _RoleManager = roleManager;
        }

        //[Authorize(Policy = "claimRequirement")]
        [HttpGet]
        public async Task<IActionResult> AddUserToClaim(string id) {
            if (ModelState.IsValid) {
                if (string.IsNullOrEmpty(id)) return NotFound();
                var user = await _UserManager.FindByIdAsync(id);
                if (user == null) return NotFound();
                var allClaim = ClaimStore.AllClaims;
                var userClaims = await _UserManager.GetClaimsAsync(user);
                var validClaims = allClaim.Where(c => userClaims.All(x => x.Type != c.Type))
                    .Select(c => new ClaimViewModel(c.Type)).ToList();
                var model = new A_R_ClaimsViewModel(id, validClaims);
                return View(model);
            }
            return View();
        }

        //[Authorize(Policy = "claimRequirement")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToClaim(A_R_ClaimsViewModel model) {
            if (ModelState.IsValid) {
                if (model == null) return NotFound();
                var user = await _UserManager.FindByIdAsync(model.UserId);
                if (user == null) return NotFound();
                var requestClaim = model.UserClaims.Where(r => r.IsSelected).Select(u => new Claim(u.ClaimType, true.ToString()));
                var result = await _UserManager.AddClaimsAsync(user, requestClaim);
                if (result.Succeeded) return RedirectToAction(nameof(Index));
                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
                return View(model);
            }
            return View();
        }

        //[Authorize(Policy = "claimRequirement")]
        [HttpGet]
        public async Task<IActionResult> RemoveUserFromClaim(string id) {
            if (ModelState.IsValid) {
                if (string.IsNullOrEmpty(id)) return NotFound();
                var user = await _UserManager.FindByIdAsync(id);
                if (user == null) return NotFound();

                var userClaims = await _UserManager.GetClaimsAsync(user);
                var validClaims = userClaims.Select(c => new ClaimViewModel(c.Type)).ToList();
                var model = new A_R_ClaimsViewModel(id, validClaims);
                return View(model);
            }
            return View();
        }

        //[Authorize(Policy = "claimRequirement")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveUserFromClaim(A_R_ClaimsViewModel model) {
            if (ModelState.IsValid) {
                if (model == null) return NotFound();
                var user = await _UserManager.FindByIdAsync(model.UserId);
                if (user == null) return NotFound();
                var requestClaim = model.UserClaims.Where(r => r.IsSelected).Select(u => new Claim(u.ClaimType, true.ToString()));
                var result = await _UserManager.RemoveClaimsAsync(user, requestClaim);
                if (result.Succeeded) return RedirectToAction(nameof(Index));
                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
                return View(model);
            }
            return View();
        }
    } 
}

WebRepository/Areas/IdentityArea/Views/ManageUser/AddUserToRole.cshtml
@model AddUserToRoleViewModel
@{
    ViewData["Title"] = "AddUserToRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>AddUserToRole</h1>


@if (!Model.UserRoles.Any()) {
    <h1>هیچ مقامی یافت نشد</h1>
} else {
    <form asp-area="IdentityArea" asp-controller="ManageUser" asp-action="AddUserToRole" method="post">
        <div asp-validation-summary="ModelOnly"></div>

        @for (int i = 0; i < Model.UserRoles.Count; i++) {
            <div class="form-group">
                <input asp-for="@Model.UserRoles[i].IsSelected" />
                <label>@Model.UserRoles[i].RoleName</label>

                <input type="hidden" asp-for="@Model.UserRoles[i].RoleName" />
            </div>
        }
        <input type="hidden" asp-for="@Model.UserId" />
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
}

WebRepository/Areas/IdentityArea/Views/ManageUser/EditUser.cshtml
@model IdentityUser
@{
    ViewData["Title"] = "EditUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>EditUser</h1>

<form asp-area="IdentityArea" asp-controller="ManageUser" asp-action="EditUser" method="post">
    <div asp-validation-summary="ModelOnly"></div>

    <div class="form-group">
        <label class="control-label" asp-for="UserName"></label>
        <input class="form-control" asp-for="UserName" />
    </div>

    <input type="hidden" asp-for="Id" />

    <button class="btn btn-primary" type="submit">Submit</button>
</form>

WebRepository/Areas/IdentityArea/Views/ManageUser/Index.cshtml
@model List<IndexViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (!Model.Any()) {
    <h1>کاربری یافت نشد</h1>
} else {
    for (int i = 0; i < Model.Count; i++) {
        <div class="card mt-2">
            <div class="card-header">
                User Name : <b>@Model[i].UserName</b>
            </div>
            <div class="card-body">
                User Email : <b>@Model[i].Email</b>
            </div>
            <div class="card-footer container-fluid">
                <form asp-area="IdentityArea" asp-controller="ManageUser" asp-action="DeleteUser" asp-route-id="@Model[i].Id" method="post">
                    <div class="row">
                        <div class="col-4">
                            <a asp-area="IdentityArea" asp-controller="ManageUser" asp-action="EditUser" asp-route-id="@Model[i].Id"
                               class="btn btn-block btn-outline-warning">Edit Username</a>
                            <button type="submit" class="btn btn-block btn-danger">Delete user</button>
                        </div>
                        <div class="col-4">
                            <a asp-area="IdentityArea" asp-controller="ManageUser" asp-action="AddUserToRole" asp-route-id="@Model[i].Id"
                               class="btn btn-block btn-primary">Add to role</a>
                            <a asp-area="IdentityArea" -controller="ManageUser" asp-action="RemoveUserFromRole" asp-route-id="@Model[i].Id"
                               class="btn btn-block btn-danger">Remove From role</a>
                        </div>
                        <div class="col-4">
                            <a asp-area="ClaimsArea" asp-controller="Claims" asp-action="AddUserToClaim" asp-route-id="@Model[i].Id"
                               class="btn btn-block btn-outline-primary">Add to Claim</a>
                            <a asp-area="ClaimsArea" asp-controller="Claims" asp-action="RemoveUserFromClaim" asp-route-id="@Model[i].Id"
                               class="btn btn-block btn-outline-danger">Remove From Claim</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    }
}

WebRepository/Areas/IdentityArea/Views/ManageUser/RemoveUserFromRole.cshtml
@model AddUserToRoleViewModel
@{
    ViewData["Title"] = "DeleteUserToRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>DeleteUserToRole</h1>

<form asp-area="IdentityArea" asp-controller="ManageUser" asp-action="RemoveUserFromRole" method="post">
    <div asp-validation-summary="ModelOnly"></div>
    @if (!Model.UserRoles.Any()) {
        <h1>هیچ مقامی یافت نشد</h1>
    } else {
        for (int i = 0; i < Model.UserRoles.Count; i++) {
            <div class="form-group">
                <input asp-for="@Model.UserRoles[i].IsSelected" />
                <label>@Model.UserRoles[i].RoleName</label>

                <input type="hidden" asp-for="@Model.UserRoles[i].RoleName" />
            </div>
        }
    }

    <input type="hidden" asp-for="@Model.UserId" />
    <button class="btn btn-primary" type="submit">Submit</button>
</form>