WebRepository/Areas/SiteSettingArea/Controllers/SiteSettingController.cs
using System.Threading.Tasks;

using AllServises.Add;

using Microsoft.AspNetCore.Mvc;

using ModelLayer;

namespace WebRepository.Areas.SiteSettingArea.Controllers {
    public class SiteSettingController : Controller {

        private readonly AddService _Service;

        public SiteSettingController(AddService service) {
            _Service = service;
        }

        public async Task<IActionResult> Index() {
            return View(await _Service.GetSiteSetting());
        }

        [HttpGet]
        public IActionResult RoleValidationGuid() {
            return View(_Service.GetRoleValidationGuid());
        }
        [HttpPost]
        public IActionResult RoleValidationGuid(RoleValidationGuidViewModel model) {
            _Service.GetRoleValidationGuid(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebRepository/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> SignInManager
@inject IAuthorizationService AuthorizationService
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodingElites.ir</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/icons-1.0.0-alpha/docs/static/assets/css/bootstrap.css" rel="stylesheet" />
</head>
<body dir="rtl">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 bg-dark">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav flex-grow-1">
                    @if (SignInManager.IsSignedIn(User)) {
                        <li class="nav-item">
                            <form asp-controller="Account" asp-action="LogOut" method="post">
                                <button type="submit" class="btn btn-outline-danger text-dark">خروج</button>
                            </form>
                        </li>
                    } else {
                        <li class="nav-item pl-5">
                            <a class="btn btn-outline-success" asp-area="" asp-controller="Account" asp-action="Register"> ساخت اکانت</a>
                        </li>
                        <li class="nav-item ">
                            <a class="btn btn-outline-dark" asp-area="" asp-controller="Account" asp-action="Login">ورود به اکانت</a>
                        </li>
                    }
                </ul>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="CategoryArea" asp-controller="Categories" asp-action="SubIndex">دسته بندی</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="IdentityArea" asp-controller="ManageUser" asp-action="Index">مدریت کاربران</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="IdentityArea" asp-controller="ManageRole" asp-action="Index">مدریت رول ها</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="SiteSettingArea" asp-controller="Role" asp-action="Index">مدریت</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="SiteSettingArea" asp-controller="SiteSetting" asp-action="Index">مدریت</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>